### ISSUE TITLE
Can't paste text inside field

### ISSUE THREAD

**Issue by 8lall0** [mjl-/duit#12]
I'm on windows, when i paste something it shows a square character.

**Comment by ghost** [comment]
This reminds me.. there was an issue about changing the way suite run on windows. Do you know what I mean ? Has this happened ?

**Comment by 8lall0** [comment]
I have no idea what you are talking about

**Comment by ghost** [comment]
Devdraw is what it's called in the readme.

I never was able to get suit working on windows.

Does this ring any bells ?

**Comment by 8lall0** [comment]
Yeah, i'm using a fork of duit, the @ktye one.

**Comment by ktye** [comment]
Copy/paste are currently mapped to the Command key not the Control key:
https://github.com/mjl-/duit/blob/master/field.go#L455
It is not triggered on windows.

If you change the case to `Ctrl & 'c'` than it should trigger.

**Comment by 8lall0** [comment]
@ktye nice, thank you.
Do you think that this "windows support" would be a nice addition to duit?
